### ISSUE TITLE
Unable to import VMF map from gmod

### ISSUE THREAD

**Issue by SavantSusi** [lasa01/Plumber#158]
**Describe the bug**
Unable to import vmf file, shows an error

**To Reproduce**
1. Import a vmf file
2. See error

**Expected behavior**
It'll show the error

**Related files**
custom gmod map

**Logs**
```
bpy.ops.wm.blend_strings_utf8_validate()
bpy.context.space_data.recent_folders_active = 0
Python: Traceback (most recent call last):
  File "/home/susiterry/.config/blender/3.4/scripts/addons/io_import_vmf/__init__.py", line 728, in execute
    fs = self.get_filesystem(context)
  File "/home/susiterry/.config/blender/3.4/scripts/addons/io_import_vmf/__init__.py", line 475, in get_filesystem
    return game_def.get_indexed_filesystem()
  File "/home/susiterry/.config/blender/3.4/scripts/addons/io_import_vmf/__init__.py", line 263, in get_indexed_filesystem
    for dir_entry in os.scandir(wildcard_dir.dirpath):
FileNotFoundError: [Errno 2] No such file or directory: ''

**Details (please complete the following information):**
 - OS: Windows and Linux
 - Blender Version: 3.4.1
 - Addon Version: 0.6.9
 - Downloaded a release for the respective operating system and the source code
 - Related Game: Garry's Mod
![Screenshot_20230322_072558](https://user-images.githubusercontent.com/58572654/226905709-adeb41ee-ee5f-481c-bfb7-03462a2b1182.png)

**Comment by lasa01** [comment]
This looks like you have an empty entry in wildcard directories in the game configuration. You need to remove it from the addon preferences. If you're having further trouble with game configuration I recommend you try the Plumber beta release from the releases tab, since it can automatically configure games correctly.

**Comment by lasa01** [comment]
Closing due to inactivity.
