### ISSUE TITLE
无法导入开头w模型文件.

### ISSUE THREAD

**Issue by xajksdgas** [lasa01/Plumber#161]
错误提示
Python: Traceback (most recent call last):
  File "C:\Users\wang\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_import_vmf\__init__.py", line 1135, in execute
    qc_importer.get(name, context.collection, context)
  File "C:\Users\wang\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_import_vmf\import_qc.py", line 405, in get
    return self.get_smd(name, collection, context).a
  File "C:\Users\wang\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\io_import_vmf\import_qc.py", line 391, in get_smd
    raise Exception(f"model {name} hasn't been imported")
Exception: model models\weapons\沙漠之鹰\w_pist_deagle_dropped hasn't been imported

  搅拌机3.2版.   插件是最新版本

**Comment by lasa01** [comment]
Unfortunately I can only provide support in English. Seems like this is not the actual error, if you scroll up the console further it should show more descriptive errors.

**Comment by lasa01** [comment]
Closing due to inactivity.
