### ISSUE TITLE
Textures are not loading in

### ISSUE THREAD

**Issue by isknova** [lasa01/Plumber#194]
**Describe the bug**
Every time i import the VTF file into blender and enable Material Preview to see if the textures work, everything is just black

**To Reproduce**
1. Imported gm_construct_d.vmf
2. Set the game to Garry's Mod
3. Enable Material Preview
4. Everything is black, no textures show up

**Logs**
```
Traceback (most recent call last):
  File "C:\Users\[not showing this]\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\plumber\asset\__init__.py", line 55, in material
    import_material(material)
  File "C:\Users\[not showing this]\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\plumber\asset\material.py", line 57, in import_material
    setattr(material_data, property, resolve_value(value, texture_ext))
AttributeError: 'Material' object has no attribute 'shadow_method'
[Plumber] [ERROR] Asset importing errored: AttributeError: 'Material' object has no attribute 'shadow_method'
```

**Screenshots**
https://imgur.com/UnvbRsx
https://imgur.com/Vfur6sq

**Details (please complete the following information):**
 - OS: [Windows 10 22H2]
 - Blender Version: [4.3]
 - Addon Version: [1.1.1]
 - Did you download a release or build the addon yourself: [Downloaded A Release]
 - Related Game: [Garry's Mod]

**Additional information**
- I was using BSPSource 1.4.6.1 to get the VTF files (putting this here because idk if this could be the problem or not)
- this also happens with any else VTF i tested btw

**Comment by lasa01** [comment]
Thanks for reporting, fixed in the latest release
