### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by ScoutM2** [lasa01/Plumber#99]
When trying to import a VMF into blender I receive a file not sound error because it could not find the module 
Thanks in advance!

Indexing game files...
Indexing done in 5.459866762161255 s
Python: Traceback (most recent call last):
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\__init__.py", line 728, in execute
    importer = import_vmf.VMFImporter(fs, dec_models_path,
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmf.py", line 94, in __init__
    from . import import_vmt
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmt.py", line 10, in <module>
    from . import import_vtf
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vtf.py", line 4, in <module>
    from pyvtflib import VTFLib, VTFImageFlag, VTFImageFormat
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\__init__.py", line 384, in <module>
    _vtflib = CDLL(_library_path)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\bin\x64\VTFLib.dll' (or one of its dependencies). Try using the full path with constructor syntax.

location: <unknown location>:-1
Game files already indexed
Python: Traceback (most recent call last):
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\__init__.py", line 728, in execute
    importer = import_vmf.VMFImporter(fs, dec_models_path,
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmf.py", line 94, in __init__
    from . import import_vmt
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmt.py", line 10, in <module>
    from . import import_vtf
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vtf.py", line 4, in <module>
    from pyvtflib import VTFLib, VTFImageFlag, VTFImageFormat
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\__init__.py", line 384, in <module>
    _vtflib = CDLL(_library_path)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\bin\x64\VTFLib.dll' (or one of its dependencies). Try using the full path with constructor syntax.

location: <unknown location>:-1
Game files already indexed
Python: Traceback (most recent call last):
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\__init__.py", line 728, in execute
    importer = import_vmf.VMFImporter(fs, dec_models_path,
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmf.py", line 94, in __init__
    from . import import_vmt
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmt.py", line 10, in <module>
    from . import import_vtf
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vtf.py", line 4, in <module>
    from pyvtflib import VTFLib, VTFImageFlag, VTFImageFormat
  File "C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\__init__.py", line 384, in <module>
    _vtflib = CDLL(_library_path)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\aidan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\pyvtflib\bin\x64\VTFLib.dll' (or one of its dependencies). Try using the full path with constructor syntax.

location: <unknown location>:-1

**Comment by ScoutM2** [comment]
Thanks! I guess the problem was that I couldn't read
